# Promise

------

*  1.几种常见异步编程方案
>回调函数  事件监听   发布/订阅   Promise对象
### Promise对象

 
 当我们需要发送多个异步请求 并且每个请求之间需要相互依赖 那这时 我们只能 以嵌套方式来解决 形成 "回调地狱"

 在处理越多的异步逻辑时，就需要越深的回调嵌套

 这种编码模式的问题主要有以下几个：

* 代码逻辑书写顺序与执行顺序不一致，不利于阅读与维护。
* 异步操作的顺序变更时，需要大规模的代码重构。
* 回调函数基本都是匿名函数，bug 追踪困难。
* 回调函数是被第三方库代码（如上例中的 ajax ）而非自己的业务代码所调用的，造成了 IoC 控制反转。

代码臃肿。
可读性、可维护性差。
耦合度高、可复用性差。
容易滋生 bug。
异常处理很恶心，只能在回调里处理异。


Promise 处理多个相互关联的异步请求

我们Promise 可以更直观的方式  更简洁的方式   来解决 "回调地狱"


promise的三种状态

pending
fulfilled
rejected

1.promise 对象初始化状态为 pending
2.当调用resolve(成功)，会由pending => fulfilled
3.当调用reject(失败)，会由pending => rejected

// onFulfilled 是用来接收promise成功的值
// onRejected 是用来接收promise失败的原因
promise.then(onFulfilled, onRejected);

promise.then(result => { // onFulfilled
    console.log(result); // 'fulfilled' 
}, reason => { // onRejected 不会被调用
    
})

 


 // 2.原型方法
Promise.prototype.catch(onRejected)
Promise.prototype.then(onFulfilled, onRejected)

// 3.静态方法
Promise.all(iterable);
Promise.race(iterable);
Promise.reject(reason);
Promise.resolve(value);
Promise.finally(value);
 

Promise.all(iterable);
要不就全部成功
其中一个失败全部失败

返回值将会按照参数内的 promise 顺序排列，而不是由调用 promise 的完成顺序决定。


如果参数中包含非 promise 值，这些值将被忽略，但仍然会被放在返回数组中（如果 promise 完成的话）

例如:Promise.all([2,1,3]);
打印出来就是 213

如果传入的可迭代对象为空，Promise.all 会同步地返回一个已完成（resolved）状态的promise。
例如:Promise.all([]);
打印出来就是
 // logs
// Promise { <state>: "fulfilled", <value>: Array[0] }


如果所有传入的 promise 都变为完成状态，或者传入的可迭代对象内没有 promise，Promise.all 返回的 promise 异步地变为完成。
在任何情况下，Promise.all 返回的 promise 的完成状态的结果都是一个数组，它包含所有的传入迭代参数对象的值（也包括非 promise 值）。



catch() 方法返回一个Promise，并且处理拒绝的情况。它的行为与调用Promise.prototype.then(undefined, onRejected) 相同。 (事实上, calling obj.catch(onRejected) 内部calls obj.then(undefined, onRejected)).



finally() 方法返回一个Promise。在promise结束时，无论结果是fulfilled或者是rejected，都会执行指定的回调函数。这为在Promise是否成功完成后都需要执行的代码提供了一种方式。
这避免了同样的语句需要在then()和catch()中各写一次的情况。


Promise.race(iterable) 方法返回一个 promise，一旦迭代器中的某个promise解决或拒绝，返回的 promise就会解决或拒绝。

Promise.race([promise1, promise2]).then(function(value) {
  console.log(value);
  // value的值 看那一个返回的更快 根据返回的显示
});


Promise.reject(reason)方法返回一个带有拒绝原因reason参数的Promise对象。
静态函数Promise.reject返回一个被拒绝的Promise对象。通过使用Error的实例获取错误原因reason对调试和选择性错误捕捉很有帮助。


Promise.reject("Testing static reject").then(function(reason) {
  // 未被调用
}, function(reason) {
  console.log(reason); // "Testing static reject"
});






Promise.resolve(value)方法返回一个以给定值解析后的Promise 对象。但如果这个值是个thenable（即带有then方法），返回的promise会“跟随”这个thenable的对象，采用它的最终状态（指resolved/rejected/pending/settled）；如果传入的value本身就是promise对象，则该对象作为Promise.resolve方法的返回值返回；否则以该值为成功状态返回promise对象。


Promise.resolve("Success").then(function(value) {
  console.log(value); // "Success"
}, function(value) {
  // 不会被调用
});


 参考地址
 掘金：
 https://juejin.im/post/5cf7857ff265da1bac4005b2

参考MDN
 https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/all
 